name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle for arm32
      run: ./gradlew assembleArm32Debug

    - name: Build with Gradle for arm64
      run: ./gradlew assembleArm64Debug

    - name: Upload arm32 APK
      uses: actions/upload-artifact@master
      with:
        name: app-debug-arm32
        path: app/build/outputs/apk/arm32/debug/app-arm32-debug.apk
        
    - name: Upload arm64 APK
      uses: actions/upload-artifact@master
      with:
        name: app-debug-arm64
        path: app/build/outputs/apk/arm64/debug/app-arm64-debug.apk